package com.sarality.sync;

import com.sarality.sync.data.SyncError;

import java.util.List;

/**
 * generates API Request objects from the source domain data objects
 *
 * @param <S> this is the collected source domain object that needs to be sent to the API
 * @param <R> this is the type of the request object that is generated by the implementor class. This corresponds to
 *            a class in the model described by the client library generated by the Google Cloud Endpoints Framework
 * @author satya@ (Satya Puniani)
 */
public interface APISyncRequestGenerator<S, R, X extends SyncError> {
  /**
   * Given the collected local data object of type S, returns the generated request object of type R that should be
   * sent to the
   * cloud API
   *
   * @param sourceData local data object of type S
   * @return request object of type R
   */
  R generateSyncRequest(S sourceData);


  /**
   * Indicates if there were errors in the request generation that need to be logged
   *
   * @return true if there are errors, false for no errors
   */

  boolean hasErrors();

  /**
   * Allows caller to retrieve the errors for logging and follow up
   *
   * @return List of errors
   */
  List<X> getSyncErrors();
}
