package com.sarality.sync;

import java.util.List;

/**
 * generates API Request objects from the source domain data objects
 *
 * @author satya@ (Satya Puniani)
 * @param <T> this is the type of the source domain object that needs to be sent to the API
 * @param <R> this is the type of the request object that is generated by the implementor class. This corresponds to
 *           a class in the model described by the client library generated by the Google Cloud Endpoints Framework
 */
public interface APISyncRequestGenerator<T, R> {


  /**
   * Initialize the request generator taking in a list of T that needs to be synced with the cloud API.
   * Creates a list of request Objects of type R
   *
   * @param dataList this is the list of T that is returned by the SyncFetcher
   */
  void init(List<T> dataList);

  /**
   * Given the local Id, returns the request object of type R that should be sent to the cloud API
   *
   * @param objectId local Id of object of T
   * @return request object of type R
   */
  R generateSyncRequest(Long objectId);

  /**
   * Given the local data object of type T, returns the generated request object of type R that should be sent to the
   * cloud API
   *
   * @param sourceData local data object of type T
   * @return request object of type R
   */
  R generateSyncRequest(T sourceData);

}
