package com.sarality.sync;

/**
 * generates API Request objects from the source domain data objects
 *
 * @author satya@ (Satya Puniani)
 * @param <S> this is the collected source domain object that needs to be sent to the API
 * @param <R> this is the type of the request object that is generated by the implementor class. This corresponds to
 *           a class in the model described by the client library generated by the Google Cloud Endpoints Framework
 */
public interface APISyncRequestGenerator<S, R> {
  /**
   * Given the collected local data object of type S, returns the generated request object of type R that should be
   * sent to the
   * cloud API
   *
   * @param sourceData local data object of type S
   * @return request object of type R
   */
  R generateSyncRequest(S sourceData);

  // TODO(@Satya) implement a globalId Manager for getting globalId from localId
}
